#!/usr/bin/env python

import subprocess
from urllib.parse import urlparse
from urllib.parse import parse_qs
import os
import sys

url = sys.argv[1]
parsed_url = urlparse(url)
params = parse_qs(parsed_url.query)
# print("params:", params)

project_path = os.path.expanduser(params["project_path"][0])

file_path = params["file_path"][0]
if file_path.startswith("~"):
    file_path = os.path.expanduser(file_path)
elif file_path.startswith("/"):
    pass
else:
    file_path = project_path + "/" + file_path

cmd = []
ide = params["ide"][0]
match ide:
    case "clion":  # https://aur.archlinux.org/packages/clion-eap
        cmd.append("clion-eap")
    case "datagrip":  # https://aur.archlinux.org/packages/datagrip-eap
        cmd.append("datagrip-eap")
    case "dataspell":  # https://aur.archlinux.org/packages/dataspell-eap
        cmd.append("dataspell-eap")
    case "goland":  # https://aur.archlinux.org/packages/goland-eap
        cmd.append("goland-eap")
    case "idea":
        if os.path.exists("/usr/bin/" + "idea-ue-eap"):
            cmd.append("idea-ue-eap")  # https://aur.archlinux.org/packages/intellij-idea-ue-eap
        elif os.path.exists("/usr/bin/" + "idea"):
            cmd.append("idea")  # https://archlinux.org/packages/extra/x86_64/intellij-idea-community-edition/
        else:
            raise ValueError("Could not find binary file for idea.")
    case "phpstorm":  # https://aur.archlinux.org/packages/phpstorm-eap
        cmd.append("phpstorm-eap")
    case "pycharm":
        if os.path.exists("/usr/bin/" + "pycharm-eap"):
            cmd.append("pycharm-eap")  # https://aur.archlinux.org/packages/pycharm-eap
        elif os.path.exists("/usr/bin/" + "pycharm"):
            cmd.append("pycharm")  # https://aur.archlinux.org/packages/pycharm and https://archlinux.org/packages/extra/x86_64/pycharm-community-edition/
        else:
            raise ValueError("Could not find binary file for pycharm.")
    case "rider":  # https://aur.archlinux.org/packages/rider-eap
        cmd.append("rider-eap")
    case "rubymine":  # https://aur.archlinux.org/packages/rubymine-eap
        cmd.append("rubymine-eap")
    case "rustrover":  # https://aur.archlinux.org/packages/rustrover-eap
        cmd.append("rustrover-eap")
    case "webstorm":  # https://aur.archlinux.org/packages/webstorm-eap
        cmd.append("webstorm-eap")
    case "writerside":
        cmd.append("writerside-eap")
    case _:
        raise ValueError(f"Unrecognized value in \"ide\" parameter: \"{ide}\".")

cmd.append(project_path)
cmd.append(file_path)

cmd.append("&")  # to release the current process, in case the ide is just launched (i.e., there was no running instance of ide before launch current script)
cmd = " ".join(cmd)

# print(f"cmd: {cmd}")
subprocess.run(cmd, shell=True)
