#!/usr/bin/env python

import subprocess
from urllib.parse import urlparse
from urllib.parse import parse_qs
import os
import sys

url = sys.argv[1]
parsed_url = urlparse(url)
params = parse_qs(parsed_url.query)
# print("params:", params)

project_path = os.path.expanduser(params["project_path"][0])

file_path = params["file_path"][0]
if file_path.startswith("~"):
    file_path = os.path.expanduser(file_path)
elif file_path.startswith("/"):
    pass
else:
    file_path = project_path + "/" + file_path

cmd = []
match params["ide"][0]:
    case "writerside":
        cmd.append("writerside-eap")
        cmd.append(project_path)
        cmd.append(file_path)
    case _:
        raise ValueError


cmd.append("&")  # to release the current process, in case the ide is just launched (i.e., there was no running instance of ide before launch current script)
cmd = " ".join(cmd)

# print(f"cmd: {cmd}")
subprocess.run(cmd, shell=True)
